title: Bendeguz Borbely-Ipkovich
position: Physics BSc @ ETH Zurich
#affiliation: TBD
email: borbely06@protonmail.com
keywords: minimal academic
github_link: https://github.com/bendeguz06
linkedin: https://www.linkedin.com/in/bendeguz-borbely-ipkovich-4996bb3b3/
youtube: https://www.youtube.com/@bendeguz06
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
canonical: https://bendeguz06.github.io/
remote_theme: yaoyao-liu/strata-academic
